adding ingredients and method templates
irishdistillers/sir-trevor-twig-bundle pull request #4
Opened 2017-07-17 14:19 UTC by maxblack72

2017-07-17 14:33 UTC, hermzz approved these changes

2017-07-19 07:33 UTC, mcvicar commented
Would it be worth marking up both these lists with Schema.org Recipe properties? e.g. [recipeIngredient](http://schema.org/recipeIngredient) and [recipeInstructions](http://schema.org/recipeInstructions)

2017-07-19 07:41 UTC, hermzz commented
Yes it would!

2017-07-19 07:41 UTC, hermzz requested changes
Add schema.org properties.

2017-07-21 10:07 UTC, hermzz approved these changes

2017-07-21 10:08 UTC, merged